# Generated by Django 5.1.1 on 2025-01-04 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("avatar", models.FileField(upload_to="avatar/", verbose_name="头像")),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "员工"), ("leader", "领导")],
                        max_length=12,
                        verbose_name="角色",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="标题")),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userinfo",
                        verbose_name="审批者",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "待审批"), (2, "通过"), (3, "不通过")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("create_date", models.DateTimeField(verbose_name="创建时间")),
                (
                    "update_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "tpl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.template",
                        verbose_name="模板",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaders",
                        to="web.userinfo",
                        verbose_name="审批者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="web.userinfo",
                        verbose_name="发起者",
                    ),
                ),
            ],
        ),
    ]
