# Generated by Django 5.1.1 on 2025-01-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_order_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
