# Generated by Django 5.1.1 on 2025-01-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_order_files"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Info",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="avatar",
            field=models.FileField(
                default="avatar/默认头像.png", upload_to="avatar/", verbose_name="头像"
            ),
        ),
    ]
