# Generated by Django 5.1.1 on 2025-01-06 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="web.userinfo",
                verbose_name="收信人",
            ),
        ),
    ]
