# Generated by Django 5.1.1 on 2025-01-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_alter_message_receiver"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["is_read", "-created_at"]},
        ),
    ]
